set -g @bg "#262626"
set -g @fg "#616161"
set -g @muted_fg "#bbb903"
set -g @muted_bg "#353536"
set -g @separator "#262626"
set -g @active_bg "#bbb903"
set -g @active_fg "#353536"

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#{@bg},fg=#{@fg}"
set -g message-style "fg=#{@active_fg}, bg=#{@active_bg}"

set -g status-left-length 100
set -g status-right-length 100
set -g window-status-separator ""

set -g status-left "#[bold] [tmux] #[bg=#{@separator},fg=#{@bg}]"

set -g window-status-format "#[fg=#{@muted_bg}, bg=#{@separator}] #[fg=#{@muted_fg},bg=#{@muted_bg}]#[fg=#{@muted_fg},bg=#{@muted_bg}]#I:#W #[fg=#{@muted_bg},bg=#{@separator}]"
set -g window-status-current-format "#[fg=#{@active_bg},bg=#{@separator},bold] #[fg=#{@active_fg},bg=#{@active_bg},bold]#I:#W #[fg=#{@active_bg},bg=#{@separator}]"

set -g status-right " "

