set -sg escape-time 0
set -g mode-keys vi
set-option -g status-position bottom
set -g history-limit 2000


# Set leader
set -g prefix C-s
# Setting tmux-motion keybindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Setting split pane resize keybindings
bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5
bind-key -r C-l resize-pane -R 5

# Setting to open/split window in cur dir
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'sarve-shreyas/tmux-unique-sessions'
set -g @plugin 'tmux-unique-sessions'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-save-interval '15'

## Sourcing files
# source-file ~/.config/tmux/theme.conf


### Sourcing tmux plugins
run '~/.tmux/plugins/tpm/tpm'
run ~/.config/tmux/vendor/status/status.tmux


# Set prefix + r tmux.conf to reload the config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

